apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
- ../../base

  
patches:

- path: ./patches/deployment-patch.yaml
  target:
    kind: Deployment
    version: v1


images:
- name: nginx
  newTag: 1.25.2
